config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employment.rb
class Employment < ApplicationRecord
  # validations
  validates_presence_of :start_date, :end_date
  #associations
  belongs_to :person
end

app/models/person.rb
class Person < ApplicationRecord
  #validations
  validates_presence_of :firstname, :lastname, :email, :phone

  #associations
  has_one :employment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    # @products = Product.order(id: :desc)
  end

  def new
    @person = Person.new 
  end

  def create
    binding.pry
    @person = Person.new(person_params)
    if @person.save
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: [
            # turbo_stream.update("flash", partial: "shared/flash", locals: { notice: "Person record created" }),
            # turbo_stream.update("user-about", partial: "users/about", locals: { user: current_user })
          ]
        end
        format.html do
          redirect_to people_path, notice: "Person record created"
        end
      end
    else
      render :form_update, status: :unprocessable_entity
    end
  end

  # def edit
  #   @product = Product.find(params[:id])
  # end

  # def update
  #   @product = Product.find(params[:id])

  #   if @product.update(product_params)
  #     redirect_to products_path
  #   else
  #     render :form_update, status: :unprocessable_entity
  #   end
  # end

  # def destroy
  #   Product.destroy(params[:id])
  #   redirect_to products_path
  # end

  private

  def person_params
    params.require(:person).permit(:firstname, :lastname, :email, :nickname, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(model, key)
    tag.div(class: "mt-2 form-error") do
      model.errors.messages_for(key).join(", ")
    end
  end
end

app/views/application/_remote_modal.html.slim
= turbo_frame_tag "remote_modal" do
  .modal.fade(tabindex="-1" data-controller="remote-modal"
    data-action="turbo:before-render@document->remote-modal#hideBeforeRender")
    .modal-dialog
      .modal-content
        .modal-header
          h5.modal-title= title
          button(type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close")
        .modal-body#remote_modal_body
          = yield

app/views/home/index.html.slim
= link_to 'Personal Details', new_person_path, class: "btn btn-primary", data: { turbo_frame: "remote_modal" }

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | RemoteModalHotwireBootstrap
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    link[href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"]
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body.container.mt-4[data-controller="form-validation"]
    = yield
    = turbo_frame_tag "remote_modal", target: "_top"

app/views/people/_form.html.slim
= form_with(model: person, data: { form_validation_target: "form" }) do |f|
  .mb-3
    = f.label :firstname, class: "form-label"
    = f.text_field :firstname, class: "form-control", data: { action: "keyup->form-validation#handleValidation" }
    = errors_for person, :firstname
  .mb-3
    = f.label :lastname, class: "form-label"
    = f.text_field :lastname, class: "form-control", data: { action: "keyup->form-validation#handleValidation" }
    = errors_for person, :lastname
  .mb-3
    = f.label :nickname, class: "form-label"
    = f.text_field :nickname, class: "form-control", data: { action: "keyup->form-validation#handleValidation" }
    = errors_for person, :nickname
  .mb-3
    = f.label :email, class: "form-label"
    = f.email_field :email, class: "form-control", data: { action: "keyup->form-validation#handleValidation" }
    = errors_for person, :email
  .mb-3
    = f.label :phone, class: "form-label"
    = f.text_field :phone, class: "form-control", data: { action: "keyup->form-validation#handleValidation" }
    = errors_for person, :phone
  .mb-3.float-right
    = f.submit "Save", class: "btn btn-primary", disabled: true
    = link_to "Cancel", root_path, class: "btn btn-outline-secondary"

app/views/people/edit.html.slim
= render "remote_modal", title: "Edit product" do
  = render "form", product: @product

app/views/people/form_update.turbo_stream.slim
<%= turbo_stream.update "remote_modal_body" do %>
  <%= render "form", person: @person %>
<% end %>

app/views/people/new.html.slim
= render "remote_modal", title: "Personal Details" do
  div[data-form-validation-target="output" data-form-validation-url-value="<%= person_path %>"]
  = render "form", person: @person